# Site settings
title: My GitHub Site
description: >- 
  This is a website powered by Jekyll using the Chirpy theme.
url: "https://bencehamrak.github.io"  # Your domain or GitHub Pages URL
baseurl: ""  # If this is your main GitHub Pages site, leave as ""

# Author details
author:
  name: Bence Hamrak
  email: hamrak_bence@phd.ceu.edu

# Social media
social:
  twitter: your-twitter-handle
  github: bencehamrak

# Other settings for customizing Chirpy, such as pagination, comments, etc.

