title: Bence Hamrak
logo: /assets/icons/logo.jpeg
description: Research Fellow, European University Institute
theme: jekyll-theme-minimal
sass:
  custom_css: /assets/css/style.scss
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
