title: Bence Hamrák
logo: /assets/icons/logo.jpeg
description: Postdoctoral Researcher, University of Vienna
theme: jekyll-theme-minimal
sass:
  custom_css: /assets/css/style.scss
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
